# Generated by Django 5.0.1 on 2024-01-30 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_id_music_playlist_id_music_deezer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='id_music_deezer',
            field=models.BigIntegerField(),
        ),
    ]
